apiVersion: v1
kind: Service
metadata:
  name: coursesapi
spec:
  selector:
    app: coursesapi
  ports:
    - protocol: TCP
      port: 5081
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursesapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coursesapi
  template:
    metadata:
      labels:
        app: coursesapi
    spec:
      containers:
        - name: coursesapi
          image: <your_registry>/coursesapi
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__CoursesAPIContext
              value: "Server=sqldata;Database=CoursesDB;User Id=sa;Password=My!P@ssw0rd1;Encrypt=False"
            - name: MessageBroker__Host
              value: "amqp://armzaj:Slaptazodis!1@rabbitmq:5672"
