apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  type: LoadBalancer
  ports:
    - name: "5083"
      port: 5083
      targetPort: 8080
  selector:
    io.kompose.service: apigateway
status:
  loadBalancer: {}
