apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          image: zarminas/apigateway:v1
          name: apigateway
          ports:
            - containerPort: 8080
              hostPort: 5083
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
