version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=armzaj
      - RABBITMQ_DEFAULT_PASS=Slaptazodis!1
    ports:
      - "15672:15672"
      - "5672:5672"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=My!P@ssw0rd1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - lab2-sqldata:/var/opt/mssql

  coursesapi:
    image: zarminas/coursesapi
    build:
      context: .
      dockerfile: CoursesAPI/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CoursesAPIContext=Server=sqldata;Database=CoursesDB;User Id=sa;Password=My!P@ssw0rd1;Encrypt=False
      - MessageBroker__Host=amqp://armzaj:Slaptazodis!1@rabbitmq:5672
    ports:
       - "5081:8080"

  studentsapi:
    image: zarminas/studentsapi
    build:
      context: .
      dockerfile: StudentsAPI/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__StudentsAPIContext=Server=sqldata;Database=StudentDB;User Id=sa;Password=My!P@ssw0rd1;Encrypt=False
      - MessageBroker__Host=amqp://armzaj:Slaptazodis!1@rabbitmq:5672
    ports:
      - "5082:8080"

  apigateway:
    image: zarminas/apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5083:8080"

volumes:
  lab2-sqldata:
    external: false
