apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: coursesapi
  name: coursesapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coursesapi
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: coursesapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__CoursesAPIContext
              value: Server=sqldata;Database=CoursesDB;User Id=sa;Password=P@ssw0rd123!;Encrypt=False
            - name: MessageBroker__Host
              value: amqp://armzaj:Slaptazodis!1@rabbitmq:5672
          image: zarminas/coursesapi:v1
          name: coursesapi
          ports:
            - containerPort: 8080
              hostPort: 5081
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
