apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: coursesapi
  name: coursesapi
spec:
  type: LoadBalancer
  ports:
    - name: "5081"
      port: 5081
      targetPort: 8080
  selector:
    io.kompose.service: coursesapi
status:
  loadBalancer: {}
