apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sqldata
  name: sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqldata
  strategy:
    type: Recreate
  template:
    metadata:

      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: sqldata
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: P@ssw0rd123!
          image: mcr.microsoft.com/mssql/server:2019-latest
          name: sqldata
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources: {}
          #volumeMounts:
            #- mountPath: /var/opt/mssql
              #name: lab2-sqldata
      restartPolicy: Always
      #volumes:
        #- name: lab2-sqldata
          #persistentVolumeClaim:
            #claimName: lab2-sqldata
status: {}
