apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: studentsapi
  name: studentsapi
spec:
  ports:
    - name: "5082"
      port: 5082
      targetPort: 8080
  selector:
    io.kompose.service: studentsapi
status:
  loadBalancer: {}
