apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\armin\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: studentsapi
  name: studentsapi
spec:
  ports:
    - name: "5082"
      port: 5082
      targetPort: 8080
  selector:
    io.kompose.service: studentsapi
status:
  loadBalancer: {}
