apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\armin\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: studentsapi
  name: studentsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: studentsapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\armin\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: studentsapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__StudentsAPIContext
              value: Server=sqldata;Database=StudentDB;User Id=sa;Password=My!P@ssw0rd1;Encrypt=False
            - name: MessageBroker__Host
              value: amqp://armzaj:Slaptazodis!1@rabbitmq:5672
          image: studentsapi
          name: studentsapi
          ports:
            - containerPort: 8080
              hostPort: 5082
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
